// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmgzfuvggjhjjbdjpftc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tZ3pmdXZnZ2poampiZGpwZnRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4Mjk2MTYsImV4cCI6MjA2NDQwNTYxNn0.legyyn3Kvmwl8Z-0e73DQub2Yl_F1Su_G83nQhIEKcs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);